# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('ERP', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('quota', models.CharField(max_length=15, null=True)),
                ('quotanum', models.IntegerField(default=0)),
                ('unit', models.CharField(default='个', max_length=4)),
                ('price', models.FloatField(null=True)),
                ('devimg', models.ImageField(null=True, upload_to='')),
                ('devclass', models.CharField(max_length=15, null=True)),
                ('usesys', models.CharField(max_length=15, null=True)),
                ('usepart', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ERP', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=15, null=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
