# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20171225_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devclass',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='devimg',
            field=models.ImageField(blank=True, upload_to='screenshots'),
        ),
        migrations.AlterField(
            model_name='device',
            name='quota',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='usepart',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='usesys',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ERP',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Device'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(default='ERP库', max_length=15),
        ),
    ]
