# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20171227_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devimg',
            field=models.ImageField(blank=True, default='screenshots/default.jpg', upload_to='screenshots'),
        ),
    ]
