# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180102_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devimg',
            field=models.ImageField(default='screenshots/default.jpg', null=True, upload_to='screenshots'),
        ),
    ]
