# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20180102_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devimg',
            field=models.ImageField(blank=True, default='screenshots/68318509ly1fdmfaskbj8j20dc09sdjr.jpg', upload_to='screenshots'),
        ),
    ]
