# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20180102_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devimg1',
            field=models.ImageField(blank=True, default='screenshots/default.jpg', upload_to='screenshots'),
        ),
        migrations.AddField(
            model_name='device',
            name='devimg2',
            field=models.ImageField(blank=True, default='screenshots/default.jpg', upload_to='screenshots'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devimg',
            field=models.ImageField(blank=True, default='screenshots/default.jpg', upload_to='screenshots'),
        ),
    ]
