# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20180219_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devthumb',
            field=models.ImageField(blank=True, default='thumb/default.jpg', upload_to='thumb'),
        ),
        migrations.AddField(
            model_name='device',
            name='devthumb1',
            field=models.ImageField(blank=True, default='thumb/default.jpg', upload_to='thumb'),
        ),
        migrations.AddField(
            model_name='device',
            name='devthumb2',
            field=models.ImageField(blank=True, default='thumb/default.jpg', upload_to='thumb'),
        ),
    ]
