# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20180304_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='devthumb1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='devthumb2',
        ),
    ]
