# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20180304_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devthumb',
            field=models.ImageField(blank=True, default='thumb/default.thumb.jpg', upload_to='thumb'),
        ),
    ]
